apiVersion: v2
name: fedbox-codeserver
description: run code-server on kubernetes on cloud hypervisor or without
type: application
version: 0.1.7
appVersion: "latest"
home: https://github.com/smerschjohann/containers
sources:
  - https://github.com/smerschjohann/containers