apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.domain }}`)
    kind: Rule
    services:
    - name: {{ .Release.Name }}-{{ include "fedbox-codeserver.serviceSuffix" . }}
      namespace: {{ .Release.Namespace }}
      port: 80
  {{- if .Values.forwardports }}
  {{- range $i, $p := .Values.forwardports }}
  - match: Host(`{{ $.Values.portHostCode | replace "{{port}}" (printf "%v" $p) }}`)
    kind: Rule
    services:
    - name: {{ printf "%s-forwards" $.Release.Name | trunc 63 | trimSuffix "-" }}
      namespace: {{ $.Release.Namespace }}
      port: {{ $p }}
  {{- end }}
  {{- else if .Values.portHostRegex }}
  - match: HostRegexp(`{{ .Values.portHostRegex }}`)
    kind: Rule
    services:
    - name: {{ .Release.Name }}-{{ include "fedbox-codeserver.serviceSuffix" . }}
      namespace: {{ .Release.Namespace }}
      port: 80
  {{- end }}
  tls:
    domains:
      - {}