name: Build, Merge, and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tasks:
        description: 'JSON string representing the tasks to be run.'
        required: true
        default: >
          [{"name": "fedbox", "dir": "./images/fedbox", "target": "fedbox"},
           {"name": "fedbox-codeserver", "dir": "./images/fedbox", "target": "fedbox-codeserver"}]

env:
  DEFAULT_TASKS: >
    [{"name": "fedbox", "dir": "./images/fedbox", "target": "fedbox"},
     {"name": "fedbox-codeserver", "dir": "./images/fedbox", "target": "fedbox-codeserver"}]
  REGISTRY_REPO: 'ghcr.io/${{ github.repository }}'
  TAG: 'latest'


jobs:
  build:
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            platform: "linux/amd64"
          - os: "ARM64"
            platform: "linux/arm64"
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - name: Log in to ghcr.io
        run: echo ${{ secrets.GITHUB_TOKEN }} | buildah login --password-stdin ghcr.io
      - name: Install jq
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Build and push containers
        env:
          TASKS: ${{ github.event_name == 'push' && env.DEFAULT_TASKS || github.event.inputs.tasks }}
          PLATFORM: ${{ matrix.platform }}
          ARCH: ${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
        run: |
          tasks=$(echo "$TASKS" | jq -c '.[]')
          for task in $tasks; do
            name=$(echo $task | jq -r '.name')
            dir=$(echo $task | jq -r '.dir')
            target=$(echo $task | jq -r '.target')
            image_name="$REGISTRY_REPO/$name"
            
            buildah bud \
              --platform $PLATFORM \
              -f $dir/Dockerfile \
              --format docker \
              --tls-verify=true \
              -t $image_name:$ARCH-$TAG \
              --target $target \
              --layers \
              $dir
            
            buildah push $image_name:$ARCH-$TAG docker://$image_name:$ARCH-$TAG
          done

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Merge & push manifests
        env:
          TASKS: ${{ github.event_name == 'push' && env.DEFAULT_TASKS || github.event.inputs.tasks }}
        run: |
          tasks=$(echo "$TASKS" | jq -c '.[]')
          for task in $tasks; do
            name=$(echo $task | jq -r '.name')
            image_name="$REGISTRY_REPO/$name"
            full_manifest="$image_name:$TAG"
            
            buildah manifest rm $full_manifest > /dev/null 2> /dev/null || true
            buildah manifest create $full_manifest
            
            for arch in "amd64" "arm64"; do
              buildah pull --arch $arch $full_manifest-$arch-$TAG
              buildah manifest add $full_manifest docker://$full_manifest-$arch-$TAG
            done
            
            buildah manifest push --rm --all $full_manifest docker://$full_manifest
          done