name: Build AMD64 images

permissions:
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REGISTRY_REPO: 'registry.tty0.it'
  TAG: 'latest'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            platform: "linux/amd64"
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Build and push containers
        env:
          PLATFORM: ${{ matrix.platform }}
          ARCH: ${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
          username: ${{ secrets.CONTAINER_REG_USER }}
          password: ${{ secrets.CONTAINER_REG_SECRET }}
          registry: registry.tty0.it
        run: |
          echo -n $password | docker login -u $username --password-stdin $registry 
          tasks=$(jq -c '.[]' images/tasks-amd64.json)
          for task in $tasks; do
            name=$(echo $task | jq -r '.name')
            dir=$(echo $task | jq -r '.dir')
            target=$(echo $task | jq -r '.target')
            tag=$(echo $task | jq -r '.tag')
            dockerfile=$(echo $task | jq -r '.dockerfile')
            image_name="$REGISTRY_REPO/$name"
            
            if git diff --quiet --exit-code HEAD^ HEAD $dir; then
              echo "Keine Änderungen in $dir, überspringe den Build-Prozess für $name"
              continue
            fi

            docker buildx build \
              -f $dir/Dockerfile \
              -t $image_name:$TAG \
              --target $target \
              --push \
              $dir
          done
