name: ci

permissions:
  packages: write

on:
  push:
  schedule:
    - cron:  '52 4 * * */2'

env:
  REGISTRY: ghcr.io

jobs:
  builder:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64,linux/amd64

      - name: Build base
        uses: docker/build-push-action@v5
        with:
          context: images/base
          push: true
          platforms: linux/arm64,linux/amd64
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/base:latest

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: images/code-server
          push: true
          platforms: linux/arm64,linux/amd64
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/code-server:latest


  
